parameters:
    # todo - find solution without a whole override
    ezrichtext.converter.input.xhtml5.resources: "%kernel.project_dir%/vendor/contextualcode/ezplatform-content-variables/src/bundle/Resources/xsl/xhtml5/input/docbook.xsl"

    ezrichtext.validator.docbook.resources:
        - "%kernel.project_dir%/vendor/contextualcode/ezplatform-content-variables/src/bundle/Resources/schemas/docbook/ezpublish.rng"
        - "%ibexa.field_type.richtext.resources%/schemas/docbook/docbook.iso.sch.xsl"
