system:
    admin_group:
        fieldtypes:
            ezrichtext:
                custom_tags: [content_variables]
                toolbar:
                    app_custom_tags_group:
                        priority: 60
                        buttons:
                            content_variables:
                                priority: 5
