services:
    ContextualCode\EzPlatformContentVariablesBundle\REST\Controller\Collection:
        parent: Ibexa\Rest\Server\Controller
        autowire: true
        autoconfigure: false
        public: true

    ContextualCode\EzPlatformContentVariablesBundle\REST\ValueObjectVisitor\CollectionList:
        parent: Ibexa\Contracts\Rest\Output\ValueObjectVisitor
        autowire: true
        autoconfigure: false
        public: true
        tags:
            - { name: ibexa.rest.output.value_object.visitor, type: ContextualCode\EzPlatformContentVariablesBundle\REST\Values\CollectionList }

    ContextualCode\EzPlatformContentVariablesBundle\REST\ValueObjectVisitor\Collection:
        parent: Ibexa\Contracts\Rest\Output\ValueObjectVisitor
        autowire: true
        autoconfigure: false
        public: true
        tags:
            - { name: ibexa.rest.output.value_object.visitor, type: ContextualCode\EzPlatformContentVariablesBundle\REST\Values\Collection }

    ContextualCode\EzPlatformContentVariablesBundle\REST\ValueObjectVisitor\Variable:
        parent: Ibexa\Contracts\Rest\Output\ValueObjectVisitor
        autowire: true
        autoconfigure: false
        public: true
        tags:
            - { name: ibexa.rest.output.value_object.visitor, type: ContextualCode\EzPlatformContentVariablesBundle\REST\Values\Variable }