services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $typeHandler: '@ezpublish.spi.persistence.legacy.content_type.handler.inner'
            $entityManager: "@contextualcode_contentvariables.doctrine.entity_manager"
            $fragmentPath: "%fragment.path%"
            
    ContextualCode\EzPlatformContentVariablesBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    ContextualCode\EzPlatformContentVariablesBundle\EventSubscriber\:
        resource: '../../EventSubscriber'
        tags: ['kernel.event_subscriber']

    ContextualCode\EzPlatformContentVariables\Variable\Value\Processor:
        arguments: [!tagged content_variables.value.callback]

    ContextualCode\EzPlatformContentVariablesBundle\Form\Type\Variable\Edit:
        arguments: ['@ContextualCode\EzPlatformContentVariables\Variable\Value\Processor']
        tags: [form.type]
    ContextualCode\EzPlatformContentVariablesBundle\Form\Type\Variable\BulkEdit:
        arguments: ['@ContextualCode\EzPlatformContentVariables\Variable\Value\Processor']
        tags: [form.type]

    ContextualCode\EzPlatformContentVariablesBundle\Service\Handler\Collection: ~
    ContextualCode\EzPlatformContentVariablesBundle\Service\Handler\Variable: ~
    ContextualCode\EzPlatformContentVariablesBundle\Form\Factory\FormFactory: ~

    ContextualCode\EzPlatformContentVariables\Menu\MainLeftSidebarBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: content_variables.menu.main.sidebar_left }
    ContextualCode\EzPlatformContentVariables\Menu\CollectionEditRightSidebarBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: content_variables.menu.collection_edit.sidebar_right }
    ContextualCode\EzPlatformContentVariables\Menu\VariableEditRightSidebarBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: content_variables.menu.variable_edit.sidebar_right }
    ContextualCode\EzPlatformContentVariables\Menu\BulkEditRightSidebarBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: content_variables.menu.bulk_edit.sidebar_right }

    ContextualCode\EzPlatformContentVariablesBundle\SiteAccessAwareEntityManagerFactory:
        arguments:
            $repositoryConfigurationProvider: "@ezpublish.api.repository_configuration_provider"
            $resolver: "@doctrine.orm.default_entity_listener_resolver"
            $settings: { debug: "%kernel.debug%", cache_dir: "%kernel.cache_dir%" }

    contextualcode_contentvariables.doctrine.entity_manager:
        class: Doctrine\ORM\EntityManagerInterface
        factory: [ '@ContextualCode\EzPlatformContentVariablesBundle\SiteAccessAwareEntityManagerFactory', 'get' ]
